#cloud-config
package_update: true
packages:
  - openjdk-17-jdk
  - wget
  - apt-transport-https
  - gnupg
  - lsb-release
  - docker.io
  - unzip

runcmd:
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export PATH=$JAVA_HOME/bin:$PATH
  - echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> /etc/environment
  - echo 'export PATH=$JAVA_HOME/bin:$PATH' >> /etc/environment
  - source /etc/environment
  - java -version

  # Install Trivy
  - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | tee /etc/apt/trusted.gpg.d/trivy.asc
  - echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/trivy.list
  - apt update
  - apt install -y trivy
  - trivy --version

  # Configure Docker
  - chmod 666 /var/run/docker.sock
  - systemctl restart docker

  # Run SonarQube in Docker
  - docker run -d --name sonar -p 9000:9000 sonarqube:lts-community

  # Install Azure DevOps Agent
  - mkdir /home/azureuser/agent
  - cd /home/azureuser/agent
  - curl -o agent.tar.gz https://vstsagentpackage.azureedge.net/agent/3.231.0/vsts-agent-linux-x64-3.231.0.tar.gz
  - tar zxvf agent.tar.gz
  - ./config.sh --unattended --url "https://dev.azure.com/pavan839" --auth PAT --token "6hh2umc4gk9noucfHv6gX92ahh8E7sieTNxaE5Ml1MAT33hIRUxOJQQJ99BAACAAAAAAAAAAAAASAZDOeIGf" --pool "myagents" --agent "agent-$(hostname)" --replace
  - ./svc.sh install
  - ./svc.sh start

  # Deregister agent on VM shutdown (Auto-scale cleanup)
  - echo "[Unit]
    Description=Azure DevOps Agent Cleanup
    DefaultDependencies=no
    Before=shutdown.target reboot.target halt.target

    [Service]
    Type=oneshot
    ExecStart=/home/azureuser/agent/config.sh remove --unattended --auth PAT --token YOUR_PERSONAL_ACCESS_TOKEN
    RemainAfterExit=yes

    [Install]
    WantedBy=shutdown.target reboot.target halt.target" > /etc/systemd/system/agent-cleanup.service
  - systemctl daemon-reload
  - systemctl enable agent-cleanup.service
