apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: demoacr839.azurecr.io/demorepo-:929
        name: worker
      imagePullSecrets:
        - name: acr-secret

